# environment.yml
name: atmpy
channels:
  - conda-forge
  - defaults
dependencies:
  - cupy == 13.2
  - numpy == 1.26
  - numba == 0.60
  - scipy == 1.14.0
  - matplotlib == 3.9.1
  - pytest == 8.3.2
  - pytest-cov == 6.0.0
  - black == 24.4.2
  - flake8 ==7.1.1
  - sphinx=6.2.1
  - jupyter==1.0.0
  - sphinx-autoapi==3.2.1
  - pytest-doctestplus==0.11.1
  - pytest-mock==3.14.0
  - doctest==2.4.11
  - mypy==1.11.1
  - pip == 24.2
  - netCDF4
  - pip:
      -  sphinx-rtd-theme
      - -e .
