# environment.yml
name: atmpy
channels:
  - conda-forge
  - defaults
dependencies:
  - cupy
  - numpy
  - numba
  - scipy
  - matplotlib
  - pytest
  - pytest-cov
  - black
  - flake8
  - sphinx=6.2.1
  - jupyter
  - sphinx-autoapi
  - pytest-cov
  - doctest
  - mypy
  - pip
  - pip:
      -  sphinx-rtd-theme
      - -e .
