# environment.yml
name: atmpy
channels:
  - conda-forge
  - defaults
dependencies:
  - cupy
  - numpy
  - numba
  - scipy
  - matplotlib
  - pytest
  - black
  - flake8
  - sphinx
  - jupyter
  - pip
  - pip:
      - -e .
