name: Python Package using Conda

on: [push]

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Formatting Suite [flake8 and black]
      run: |
        # Pipeline failure with Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F8 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        # Pipeline failure with black errors
        black --check --exclude /docs .
    - name: Test Suite [pytest]
      run: |
        pytest
#    - name: Docs Suite [sphinx]
#      run: |
#        cd docs
#        make html
#
#    - name: Upload documentation artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: sphinx-docs
#        path: docs/_build/html/
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
